'use client';
import Image from 'next/image';import Link from 'next/link';import {ArrowRight,User,Clock,Shield,Folder,Image as Img,Lock,Lightbulb,Cloud,Workflow,Database,Search} from 'lucide-react';
export function Header({active=''}){const items=[['/','Start','start'],['/privatpersonen','Privatpersonen','privat'],['/unternehmen','Unternehmen','unternehmen'],['/ablauf','Ablauf','ablauf'],['/kontakt','Kontakt','kontakt']];return <header className="topbar"><div className="container nav"><Link href="/"><Image className="logo" src="/assets/logo.png" alt="OrdnungsWerk Digital" width={210} height={60}/></Link><nav className="menu">{items.map(([href,label,key])=><Link key={key} className={active===key?'active':''} href={href}>{label}</Link>)}</nav><Link className="headerbtn" href="/kontakt">Unverbindlich anfragen</Link></div></header>}
export function Footer(){return <footer className="footer"><div className="container"><strong>OrdnungsWerk Digital</strong><div><Link href="/impressum">Impressum</Link> · <Link href="/datenschutz">Datenschutz</Link></div></div></footer>}
export function Cookie(){return <div className="cookie" id="cookie"><strong>Cookie-Einstellungen</strong><p>Diese Website nutzt nur notwendige Cookies. Weitere Dienste werden erst nach Zustimmung aktiviert.</p><button className="btn" onClick={()=>{localStorage.setItem('cookie-ok','1');document.getElementById('cookie')?.classList.add('hide')}}>Verstanden</button></div>}
export function Layout({active,children}){return <><Header active={active}/>{children}<Footer/><Cookie/></>}
export function HomeHero(){return <section className="hero"><div className="container hero-inner"><div><span className="eyebrow">Digitale Ordnung, die wirklich im Alltag funktioniert</span><h1>Weniger Bürochaos.<br/>Mehr Feierabend.</h1><p className="lead">Ich helfe Privatpersonen und kleinen Unternehmen, Dokumente, Dateien und digitale Abläufe klar zu strukturieren – verständlich, sicher und ohne Technik-Überforderung.</p><div className="cta"><Link className="btn" href="/kontakt">Unverbindlich anfragen <ArrowRight size={18}/></Link><Link className="btn secondary" href="/ablauf">So läuft es ab <ArrowRight size={18}/></Link></div><div className="proofs"><div className="proof"><User size={40}/>Persönlich & verständlich</div><div className="proof"><Clock size={40}/>Für Alltag und Betrieb</div><div className="proof"><Shield size={40}/>Struktur statt Suchstress</div></div></div><div><Image className="hero-img" src="/assets/hero-desk.png" alt="Digital strukturierter Arbeitsplatz mit Laptop" width={1328} height={548} priority/></div></div></section>}
export const privateCards=[['Zu viele Dateien','Unübersichtliche Ordner und doppelte Dateien kosten Zeit und Nerven.',Folder],['Wichtige Unterlagen','Verträge, Rechnungen oder Versicherungen sind schwer auffindbar.',Img],['Unsicher bei Backups','Keine regelmäßigen Sicherungen – Datenverlust bleibt ein Risiko.',Shield],['Passwörter & Zugänge','Zu viele Konten, zu viele Passwörter – und doch den Überblick verlieren.',Lock]];
export const businessCards=[['Unstrukturierte Ablage','Dateien sind verteilt und schwer auffindbar.',Folder],['Ineffiziente Prozesse','Zu viele manuelle Schritte und Medienbrüche kosten Zeit.',Workflow],['Sicherheitsrisiken','Keine klaren Rechte, fehlende Backups und unübersichtliche Zugänge.',Shield],['Wissensverlust','Informationen sind an einzelne Personen gebunden.',Lightbulb]];
export function Cards({items}){return <div className="cards">{items.map(([h,p,Icon])=><div className="card" key={h}><Icon size={44}/><h3>{h}</h3><p>{p}</p></div>)}</div>}
export function Checks({type}){const p=['Klare Ordnerstruktur & Dateiorganisation','Wichtige Unterlagen sicher & schnell finden','Digitale Abläufe vereinfachen','Backups & Sicherheit verständlich einrichten','Passwörter sicher verwalten','Nachhaltige Lösungen, die im Alltag bleiben'];const b=['Aufbau einer klaren & logischen Struktur','Effiziente, digitale Abläufe etablieren','Dokumente sicher ablegen & finden','Zugriffsrechte & Sicherheit verbessern','Backups & Datenschutz umsetzen','Praktische Lösungen, die Ihr Team mitnimmt'];return <div className="check-grid">{(type==='business'?b:p).map(x=><p className="check" key={x}>{x}</p>)}</div>}
export function CtaStrip({business=false}){return <div className="cta-strip"><span>{business?'Gemeinsam schaffen wir eine Struktur, die bleibt.':'Lass uns gemeinsam Ordnung schaffen – Schritt für Schritt.'}</span><Link className="btn" href="/kontakt">Unverbindlich anfragen</Link></div>}
